#Embedded file name: /data/raik/py/labhamsterproject/labhamster/migrations/0001_initial.py
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        db.create_table('labhamster_order', (('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
         ('status', self.gf('django.db.models.fields.CharField')(default='pending', max_length=20)),
         ('date_created', self.gf('django.db.models.fields.DateField')(auto_now_add=True, blank=True)),
         ('date_ordered', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
         ('date_received', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
         ('created_by', self.gf('django.db.models.fields.related.ForeignKey')(related_name='requests', to=orm['auth.User'])),
         ('ordered_by', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='orders', null=True, to=orm['auth.User'])),
         ('item', self.gf('django.db.models.fields.related.ForeignKey')(related_name='orders', to=orm['labhamster.Item'])),
         ('unit_size', self.gf('django.db.models.fields.IntegerField')(default=1)),
         ('quantity', self.gf('django.db.models.fields.IntegerField')(default=1)),
         ('price', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=6, decimal_places=2, blank=True)),
         ('grant_category', self.gf('django.db.models.fields.CharField')(default='consumables', max_length=20)),
         ('grant', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='orders', null=True, to=orm['labhamster.Grant'])),
         ('comment', self.gf('django.db.models.fields.TextField')(blank=True))))
        db.send_create_signal('labhamster', ['Order'])
        db.create_table('labhamster_item', (('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
         ('name', self.gf('django.db.models.fields.CharField')(unique=True, max_length=30)),
         ('vendor', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['labhamster.Vendor'])),
         ('catalog', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True)),
         ('category', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['labhamster.Category'])),
         ('date_received', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
         ('date_expiration', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
         ('status', self.gf('django.db.models.fields.CharField')(default='out', max_length=20)),
         ('link', self.gf('django.db.models.fields.URLField')(max_length=200, blank=True)),
         ('comment', self.gf('django.db.models.fields.TextField')(blank=True)),
         ('location', self.gf('django.db.models.fields.CharField')(max_length=60, blank=True))))
        db.send_create_signal('labhamster', ['Item'])
        db.create_table('labhamster_vendor', (('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
         ('name', self.gf('django.db.models.fields.CharField')(unique=True, max_length=30)),
         ('link', self.gf('django.db.models.fields.URLField')(max_length=200, blank=True)),
         ('phone', self.gf('django.db.models.fields.CharField')(max_length=20, blank=True)),
         ('email', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True)),
         ('contact', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True))))
        db.send_create_signal('labhamster', ['Vendor'])
        db.create_table('labhamster_category', (('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)), ('name', self.gf('django.db.models.fields.CharField')(unique=True, max_length=20))))
        db.send_create_signal('labhamster', ['Category'])
        db.create_table('labhamster_grant', (('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
         ('name', self.gf('django.db.models.fields.CharField')(unique=True, max_length=40)),
         ('grant_id', self.gf('django.db.models.fields.CharField')(unique=True, max_length=30, blank=True)),
         ('comment', self.gf('django.db.models.fields.TextField')(blank=True))))
        db.send_create_signal('labhamster', ['Grant'])

    def backwards(self, orm):
        db.delete_table('labhamster_order')
        db.delete_table('labhamster_item')
        db.delete_table('labhamster_vendor')
        db.delete_table('labhamster_category')
        db.delete_table('labhamster_grant')

    models = {'auth.group': {'Meta': {'object_name': 'Group'},
                    'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
                    'name': ('django.db.models.fields.CharField', [], {'unique': 'True',
                              'max_length': '80'}),
                    'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']",
                                     'symmetrical': 'False',
                                     'blank': 'True'})},
     'auth.permission': {'Meta': {'ordering': "('content_type__app_label', 'content_type__model', 'codename')",
                                  'unique_together': "(('content_type', 'codename'),)",
                                  'object_name': 'Permission'},
                         'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
                         'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
                         'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
                         'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})},
     'auth.user': {'Meta': {'object_name': 'User'},
                   'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
                   'email': ('django.db.models.fields.EmailField', [], {'max_length': '75',
                              'blank': 'True'}),
                   'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30',
                                   'blank': 'True'}),
                   'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Group']",
                               'symmetrical': 'False',
                               'blank': 'True'}),
                   'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
                   'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
                   'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
                   'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
                   'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
                   'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30',
                                  'blank': 'True'}),
                   'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
                   'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']",
                                         'symmetrical': 'False',
                                         'blank': 'True'}),
                   'username': ('django.db.models.fields.CharField', [], {'unique': 'True',
                                 'max_length': '30'})},
     'contenttypes.contenttype': {'Meta': {'ordering': "('name',)",
                                           'unique_together': "(('app_label', 'model'),)",
                                           'object_name': 'ContentType',
                                           'db_table': "'django_content_type'"},
                                  'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
                                  'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
                                  'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
                                  'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})},
     'labhamster.category': {'Meta': {'ordering': "('name',)",
                                      'object_name': 'Category'},
                             'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
                             'name': ('django.db.models.fields.CharField', [], {'unique': 'True',
                                       'max_length': '20'})},
     'labhamster.grant': {'Meta': {'ordering': "('name', 'grant_id')",
                                   'object_name': 'Grant'},
                          'comment': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
                          'grant_id': ('django.db.models.fields.CharField', [], {'unique': 'True',
                                        'max_length': '30',
                                        'blank': 'True'}),
                          'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
                          'name': ('django.db.models.fields.CharField', [], {'unique': 'True',
                                    'max_length': '40'})},
     'labhamster.item': {'Meta': {'ordering': "('name', 'vendor')",
                                  'object_name': 'Item'},
                         'catalog': ('django.db.models.fields.CharField', [], {'max_length': '30',
                                      'blank': 'True'}),
                         'category': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['labhamster.Category']"}),
                         'comment': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
                         'date_expiration': ('django.db.models.fields.DateField', [], {'null': 'True',
                                              'blank': 'True'}),
                         'date_received': ('django.db.models.fields.DateField', [], {'null': 'True',
                                            'blank': 'True'}),
                         'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
                         'link': ('django.db.models.fields.URLField', [], {'max_length': '200',
                                   'blank': 'True'}),
                         'location': ('django.db.models.fields.CharField', [], {'max_length': '60',
                                       'blank': 'True'}),
                         'name': ('django.db.models.fields.CharField', [], {'unique': 'True',
                                   'max_length': '30'}),
                         'status': ('django.db.models.fields.CharField', [], {'default': "'out'",
                                     'max_length': '20'}),
                         'vendor': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['labhamster.Vendor']"})},
     'labhamster.order': {'Meta': {'ordering': "('date_created',)",
                                   'object_name': 'Order'},
                          'comment': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
                          'created_by': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'requests'",
                                          'to': "orm['auth.User']"}),
                          'date_created': ('django.db.models.fields.DateField', [], {'auto_now_add': 'True',
                                            'blank': 'True'}),
                          'date_ordered': ('django.db.models.fields.DateField', [], {'null': 'True',
                                            'blank': 'True'}),
                          'date_received': ('django.db.models.fields.DateField', [], {'null': 'True',
                                             'blank': 'True'}),
                          'grant': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True',
                                     'related_name': "'orders'",
                                     'null': 'True',
                                     'to': "orm['labhamster.Grant']"}),
                          'grant_category': ('django.db.models.fields.CharField', [], {'default': "'consumables'",
                                              'max_length': '20'}),
                          'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
                          'item': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'orders'",
                                    'to': "orm['labhamster.Item']"}),
                          'ordered_by': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True',
                                          'related_name': "'orders'",
                                          'null': 'True',
                                          'to': "orm['auth.User']"}),
                          'price': ('django.db.models.fields.DecimalField', [], {'null': 'True',
                                     'max_digits': '6',
                                     'decimal_places': '2',
                                     'blank': 'True'}),
                          'quantity': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
                          'status': ('django.db.models.fields.CharField', [], {'default': "'pending'",
                                      'max_length': '20'}),
                          'unit_size': ('django.db.models.fields.IntegerField', [], {'default': '1'})},
     'labhamster.vendor': {'Meta': {'object_name': 'Vendor'},
                           'contact': ('django.db.models.fields.CharField', [], {'max_length': '30',
                                        'blank': 'True'}),
                           'email': ('django.db.models.fields.CharField', [], {'max_length': '30',
                                      'blank': 'True'}),
                           'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
                           'link': ('django.db.models.fields.URLField', [], {'max_length': '200',
                                     'blank': 'True'}),
                           'name': ('django.db.models.fields.CharField', [], {'unique': 'True',
                                     'max_length': '30'}),
                           'phone': ('django.db.models.fields.CharField', [], {'max_length': '20',
                                      'blank': 'True'})}}
    complete_apps = ['labhamster']