# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labhamster', '0002_manual_rename_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text=b'Order-related remarks. Please put catalog number and descriptions not here but into the product page.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_received',
            field=models.DateField(blank=True, help_text=b'Date when product was received', null=True, verbose_name=b'received'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(help_text=b'Click the magnifying lens to select from the list of existing products.\nFor a new product, first click the lens, then click "Add Product" and fill out and save the Product form.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='labhamster.Product', verbose_name=b'Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text=b'short descriptive name of this product', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(help_text=b'select normal supplier of this product', on_delete=django.db.models.deletion.CASCADE, to='labhamster.Vendor', verbose_name=b'Vendor'),
        ),
    ]
