# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labhamster', '0004_auto_20160513_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text=b'Mark this order as urgent', verbose_name=b'Urgent!'),
        ),
        migrations.AddField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, help_text=b'', max_length=20, null=True, verbose_name=b'P.O.number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', 'Euro'), (b'GBP', 'Pound Sterling'), (b'SAR', 'Saudi Riyal'), (b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3),
        ),
    ]
