# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labhamster', '0005_auto_20180224_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text=b'original manufacturer if different', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_product', to='labhamster.Vendor', verbose_name=b'Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, help_text=b'URL Link to product description', verbose_name=b'Vendor Link'),
        ),
    ]
