# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labhamster', '0007_auto_20180224_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, help_text=b'Product web site', verbose_name=b'Product Link'),
        ),
    ]
