# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labhamster', '0009_auto_20221216_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
